development:
  adapter: postgresql
  encoding: utf8
  database: url_shortener_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: url_shortener_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: url_shortener_development
  pool: 5
  username:
  password:
